// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace Azure.AI.Language.MCP.Server.Enums.Ner
{
    /// <summary>
    /// Types of named entities that can be recognized by the Named Entity Recognition (NER) tool.
    /// </summary>
    public enum NerTypeEnum
    {
        All = 0,
        Person,
        PersonType,
        Skill,
        Address,
        DateTime,
        DateAndTime,
        Date,
        Time,
        DateTimeRange,
        DateRange,
        TimeRange,
        Duration,
        SetTemporal,
        Quantity,
        Age,
        Number,
        Percentage,
        Currency,
        Temperature,
        Ordinal,
        NumberRange,
        Dimension,
        Speed,
        Length,
        Height,
        Weight,
        Volume,
        Area,
        DigitalInformation,
        Organization,
        OrganizationStockExchange,
        OrganizationMedical,
        OrganizationSports,
        Event,
        EventSports,
        EventNatural,
        EventCultural,
        Product,
        ComputingProduct,
        Location,
        Geographical,
        Structural,
        GPE,
        City,
        State,
        CountryRegion,
        Continent,
        Airport,
        PhoneNumber,
        IPAddress,
        Email,
        URL,
    }
}