# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build binaries for Language MCP dotnet implementation
# This workflow will build a .NET project

on:
  push:
    branches: [ "main" ]
    paths: ['src/dotnet/mcp/**', '.github/workflows/build-dotnet.yaml']

  pull_request:
    branches: [ "main" ]
    paths: ['src/dotnet/mcp/**', '.github/workflows/build-dotnet.yaml']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore  src/dotnet/mcp 
    
    - name: Build
      run: dotnet build --no-restore src/dotnet/mcp --configuration Release
    
    - name: Test
      run: dotnet test src/dotnet/mcp/McpServer.Test/McpServer.Test.csproj --no-build --verbosity normal
    
    - name: Publish LanguageMcpServer win-64 server
      run: dotnet publish src/dotnet/mcp/LanguageMcpServer/LanguageMcpServer.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output ./artifacts/Server/LanguageMcpServer/win-x64
    
    - name: Publish LanguageMcpServer linux-64 server
      run: dotnet publish src/dotnet/mcp/LanguageMcpServer/LanguageMcpServer.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true --output ./artifacts/Server/LanguageMcpServer/linux-x64
    
    - name: Publish TranslatorMcpServer win-64 server
      run: dotnet publish src/dotnet/mcp/TranslatorMcpServer/TranslatorMcpServer.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output ./artifacts/Server/TranslatorMcpServer/win-x64
    
    - name: Publish TranslatorMcpServer linux-64 server
      run: dotnet publish src/dotnet/mcp/TranslatorMcpServer/TranslatorMcpServer.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true --output ./artifacts/Server/TranslatorMcpServer/linux-x64

    - name: Publish client
      run: dotnet publish src/dotnet/mcp/McpClient/ --configuration Release --output ./artifacts/McpClient
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcp-dotnet
        path: ./artifacts